### ISSUE TITLE
Proposed config file format

### ISSUE THREAD

**Issue by sjrct** [Halibot/halibot#1]
halibot.json - written by halibot user

```
{
  "module-path": [
    "modules"
  ],

  "agent-path": [
    "agents"
  ],

  "instantiated-modules": {
    "quote0": {
      "of": "quote"
    }
  },

  "instantiated-agents": {
    "irc0": {
      "of": "irc",
      "channel": "#foo"
    }
  }
}
```

irc.json, written by the agent implementer

```
{
  "name": "irc",
  "sources": [
    "irc.py"
  ]
}
```

The benefit of this is foremost distinguishing between what is written by the user, ie. `halibot.json`, and that which is written by the module/agent implementer. Names are quite open to debate.

**Comment by richteer** [comment]
Looks good, though maybe `"instantiated-modules"` could be shorted to `"load-modules"` or something similar?

Also, as this has a dependency on the new module/agent system, this will likely be implemented initially without the latter half.

**Comment by sjrct** [comment]
I am all for shorter phrases so long as the meaning is conveyed.  `load-modules` is probably better.

**Comment by richteer** [comment]
Should there be an `"include"` directive? So something like

```
{
   "config-path": [ "~/.config/halibot"],
   ...
   "instantiated-agents": {
      "irc0": {
         "of": "irc",
         "include":"ircconfig.json"
    }
  }
}

```

where, `"irc0"`'s object would be union'd with the object inscribed in `"ircconfig.json"`?

**Comment by sjrct** [comment]
It certainly could be useful. I am not going to make it a priority with the implementation I am working on now though.
