### ISSUE TITLE
Proposal for AgentCluster, a way for multiple agents to share the same connection resources

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#109]
*THIS IS A DRAFT RFC AND WILL LIKELY BE UPDATED OVER TIME*

Continuing on the discussions about module containers and containerization based on RI, this is an alternate look on how to separate "sub-agents" without having to initialize multiple agents or use tricky routing logic.

The general concept looks something like this:
```
            ____ ##halibot     -> container0
          /
IRCAgent ----- ##haltesting    -> container1
          \___ ##somethingelse -> container2
```
In this case, `IRCAgent` is the agent cluster that actually connects to the service such as freenode, and the sub-agents all serve individual channels. The sub-agents are thin agents that simply translate messages to/from `container0`, with the context of whatever that sub-agent is given.

A better example would be a more rich protocol such as discord. Each sub-agent could manage a specific server. Therefore, the AgentCluster only needs to route to the sub-agent meant to handle that particular server. Furthermore, this means each server can have its own configuration blob, which could include agent-level keys such as `"allowed-channels"`, for determining which channels as part of that server are worth monitoring.

This system can be implemented on top of the existing Halibot infrastructure with a little bit of jank -- an AgentCluster will initialize as part of the regular agent initialization chain, but during the init process, it will initialize and add all the configured sub-agents as well. Sub-agent config will be stored as a child node in the AgentCluster's config. AgentCluster implementors will also define a template for the Sub-agent behavior, again such as channel filtering, or whatever they may desire.

**Comment by richteer** [comment]
Candidate for removal, with proper RI declarations and handling, this extra layer of abstraction should not be necessary.

**Comment by sjrct** [comment]
Agree, RI and routing is the solution here.
