### ISSUE TITLE
HalAuth: Handle missing permissions.json better

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#118]
Issue #55 and PR #94 create a `permissions.json` file on first init, but if it is missing, Halibot still reports an error.

There are a few questions here:
1. ~Should the `permissions.json` file be a config item? Is there a benefit?~ This already exists [here](https://github.com/Halibot/halibot/blob/master/halibot/halibot.py#L60)
2. What should the behavior be if it is missing? Disable auth? Reject all perms? Create a new one?
3. How should Halibot report this? We report the missing file, but not how it is reacting to it.

Answers:
1. see edit above
2. If `config.json` specifies `use-auth: True` and we fail to load the permissions file, we should load a default empty permissions array, but set `auth.enabled = True`. This will effectively reject all permission checks.
3. Halibot should continue to report this as an error.

**Comment by mracine** [comment]
I can also work on this issue.

**Comment by mracine** [comment]
Is this issue satisfied by my PR? Not sure if there's something that's left or if we just forgot to close this issue.

**Comment by richteer** [comment]
Yep, mb

**Comment by sjrct** [comment]
sooo....?

**Comment by richteer** [comment]
I forgot to close it again. I wish I did that as a joke.
