### ISSUE TITLE
HalAuth: Document the HalAuth Permissions model

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#119]
Since #116 has been proposed, I suppose it is time to start paying attention to how permissions work again. Therefore, there should probably be a developer-focused document explaining how it works.

I'm tagging this issue as `easy` because I think it is a good entry point to getting into the dirty innards of Halibot. If you are interested in this issue, I'd be happy to walk you through how this model works -- feel free to ping me in `##halibot` on Freenode.

**Comment by mracine** [comment]
I'll be working on this issue.

**Comment by richteer** [comment]
Added by #124
