### ISSUE TITLE
CI: Running tests removes the IRC package, and other local-install corruptions

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#121]
All tests should be running in a totally different namespace, and NOT using the packages directory as part of the cloned repo. This is a severe bug, as it messes with the typical local Halibot development environment.

Furthermore, we shouldn't test `fetch` as part of the cli tests, since that depends on a repo server being accessible -- a failure on the side of the repo server SHOULD NOT lead to a test failure.

**Comment by richteer** [comment]
@sjrct Tagging you in this, since I think you are the one that wrote these test cases. Suggestions on how to proceed?

**Comment by richteer** [comment]
From `main.py`'s implementation of `unfetch`:
```python3
        for pkgpath in bot.config["package-path"]:
            path = os.path.join(pkgpath, name)
            if os.path.exists(path):
                shutil.rmtree(path)
                print("Removed '{}' installed to '{}'.".format(name, path))
                success = True
```

We delete packages from all applicable `package-path`s. This should most certainly not be intended.

**Comment by richteer** [comment]
Opened #122 to track this portion of the bug.

Leaving this one open since there's still work to be fixed here: CLI tests should be totally self-contained, and not affect packages outside of its path (therefore, we should probably force `package-path` to be local-only), and should not depend on remote resources to pass tests.

I'd rather see coverage decrease in `main.py` than have a test that requires a remote server to pass.

**Comment by sjrct** [comment]
The solution for tests I think would be to limit the `package-path` of ~~the test~~ all configs to only point to those for the local install.

**Comment by sjrct** [comment]
I'll work on this.
