### ISSUE TITLE
Change package's Default entry to be object-type aware

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#141]
Since packages may contain more than one `HalObject`-derived class, the `Default` setting in `__init__.py` should be a bit more flexible than only specifying a single possible object.

Take for instance, a package that provides a somewhat tightly-coupled `HalModule` and `HalAgent`. Neither should have `Default` preference over the other, so it should depend on the context of the instantiator.

Example `__init__.py`:
```python
from .foomodule import FooModule
from .fooagent import FooAgent

DefaultModule = FooModule
DefaultAgent = FooAgent
```

Example `config.json`:
```json
{
  "module-instances": {
    "foo1": {
      "of": "foo:Default" // Loads FooModule
    }
  },
  "agent-instances": {
    "foo2": {
      "of": "foo:Default" // Loads FooAgent
    }
  }
}
```

## Drawbacks
Having an explicit default module or agent does pose a clarity problem. As shown above, the configuration for the two are near identical. It is likely that the module and agent will have a different set of possible configuration keys, so keeping aware of the module version vs agent version is important.

This also is an argument against unifying the `-instance` keys into one big list, as this will add further context to how objects are loaded.

**Comment by sjrct** [comment]
What about `defaults = [ SomeModule, SomeAgent, SomeOtherModule ]`? That way it is extensible beyond just a coupled module/agent pair

**Comment by richteer** [comment]
How would that be represented in the halconfig when trying to instantiate something from the package? Sounds like more of an export list to me, which might be what we want anyway.

**Comment by sjrct** [comment]
Hmmm... yeah, fair point. Would probably have to expand module/agent names instead of using `Default` in the config.

The config from my example above would look like:
```json
{
  "module-instances": {
    "foo-module1": {
      "of": "foo:SomeModule"
    },
    "foo-module1": {
      "of": "foo:SomeOtherModule"
    }
  },
  "agent-instances": {
    "foo-agent": {
      "of": "foo:SomeAgent"
    }
  }
}
```

As to an export list, we already essentially have one. Anything in `__init__.py` is exported. The syntax for adding a non-default module/agent looks like this if I recall correctly:
```sh
halibot add SomePackage:SomeModule
```

**Comment by richteer** [comment]
Hmmm, so we should probably leave it alone then. Reading back, I agree with my concerns over clarity with overloading the "Default" for module vs agent. Closing this RFC for now then, we can reopen it in the future if we determine it necessary.
