### ISSUE TITLE
Investigation of in-place updating

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#2]
Something that was never implemented in the previous versions was the ability for the core base to reload itself. The base could reload the modules as it pleased, but not the base; this was particularly difficult as the base was also tied to the XMPP client itself.

Since the base is now separate from the agents and modules, it may be possible to restart the base (use case: API changes/fixes that do NOT break modules/agents) without disrupting the agents or modules. Final success scenario is for the running instance to reload the base source file and reinitialize the Halibot object instance.

I suspect that agents will be stable for the most part, once the API function names are stabilized, thus will likely not need to be restarted much. However, I suspect in this development phase, the base+module API will likely be in flux, thus this would be handy to avoid needless joins and parts.

**Comment by sjrct** [comment]
Maybe this could be implementing by halting all the message queues through the base, spinning up another base, shifting the queues over, and destructing the old one? Not sure how the source loading would be done though.

**Comment by richteer** [comment]
That's roughly what I was imagining, would also need to copy over any references to the loaded agents, and modify all of their references to the new base.

Source loading may be the issue though, depends on if python nicely supports a reload/refresh thing.

**Comment by richteer** [comment]
Implemented in #12
