### ISSUE TITLE
Agent, Module, etc help text and other formalities

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#21]
What metadata needs to go into these objects?

Things like:
- long/short help text
- halibot api compatibility

**Comment by richteer** [comment]
On the help text: should it be part of the module itself, or part of the module metadata? Remembering from halv2, help text was implemented like so:

``` python
class CatModule(XMPPModule):
   ...
   def help(self, feature):
        if feature in ["!cat", "cat"]:
            return '''
Usage: !cat [jpg | png | gif]
Reply with a link to a cat picture. Provide any of the three optional arguments to specify the file type.
'''
        elif feature in ["!catfact", "catfact"]:
            return '''
Usage: !catfact
Reply with a random catfact. That is all.
'''
        return '''
Because all XMPP servers need cats!
 Features:
   !cat     - Display a link to a random cat picture
   !catfact - Print a random cat fact!
'''
```

To me, stylistically, this is kind of gross looking. It probably could have been cleaned up in code, but either way, I'm wondering if we could provide a better help abstraction.

Something like:

``` python
class CatModule(CommandModule):
   SHORTHELP = "A module that spits out cat images!"
   LONGHELP = '''Replies to commands with cat images
  !cat - Display a random cat picture
  !catfact - print a random cat fact!
'''
   COMMAND_CAT_HELP = '''Usage: !cat [type]
  type - specify the image type, can be jpg, gif, or png. Default is jpg
```

or including it in the config.json that ships with the package. The idea is to have some kind of usage info for the Help module to be able to easily retrieve.

`COMMAND_CAT_HELP` would be something that the command filter would know to look for maybe?

**Comment by sjrct** [comment]
Dup of #51.
