### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by sjrct** [Halibot/halibot#23]
It is necessary to rewrite `main.py` (sensibly renamed to simply `halibot`) to incorporate a command line interface so it can be suitably installed to a `PATH` directory an run as simply `halibot`.

CLI functionality:
- ~~Run a chat bot (w/ no options)~~
- ~~Change working directory~~
- (un)install modules
- [en/dis]able modules in config (perhaps equivalent to [creat/delet]ing a titular instance)
- List installed or enabled modules

**Comment by richteer** [comment]
Might need to be some kind of shell script to kick of a repl as opposed to foregrounding
