### ISSUE TITLE
Multi-composition of Module subtypes

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#3]
How do we handle modules that want to be threaded and a command-triggered? (i.e. inherit from both ThreadedModule and CommandModule). 

Few ideas:
1. Implement the module specialties as "Interfaces", that is, stripped down classes that don't all implement the Module base class features
2. Implement interfaces in Python using some kind of fancy decorator magic to do the above, sort of
3. Not allow this (boo!)
4. Hope that multi-inheritance won't cause issues (might be fine).

Thoughts?

**Comment by sjrct** [comment]
Just thinking here, perhaps a plugin can implement two modules, one which subtypes say CommandModule and the other ThreadedModule, and the communicate to each other or to a third module? Avoids multi-inheritance.

I am not sure on how your (1) would work, could you explicate?

**Comment by richteer** [comment]
Right now, the `Module` class would provide all the basic module logic, like sending to base and receiving. `CommandModule` (name tbd) would only implement command handling logic, and NO module logic. This means it would handle the registering of commands to a `CommandBranch` if it is in one, and provides the framework to handle the routing of commands to user specified functions (as well as parsing, and so on).

Example:

``` python
class Quote(CommandModule, Module):
   def init(self):
      # Following are implemented by CommandModule
      self.register("!quote",self.quotehandler, args="string")
      self.register("!writequotes", self.writehandler, args="list")

   def quotehandler(self, string):
      self.reply(...) # Implemented by Module

   def writehandler(self, files):
      for f in files:
         with open(f, "w") as f:
            f.write(...)
```

**Comment by sjrct** [comment]
Closing due to irrelevance resulting from intended hierarchy restructure (#17).
