### ISSUE TITLE
Design and Implement a Help Text Infrastructure

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#51]
To make modules useful to users at runtime, some kind of help text should be presentable in channels, etc. This is rather open ended, but essentially users should be able to inspect what modules they can interact with, and how to interact with them.

For example, `!help` can reply with what modules are loaded, and `!help <modulename>` can reply with a short description of how to use it.

**Comment by richteer** [comment]
Halv2 implemented this by implementing a `help(arg="")` method on every module, that was called whenever `!help` was read in by halv2's core. This meant modules only had to implement that method and return their help text, halibot took care of the rest. The optional `arg` permitted the `help()` method to tailor the returned text to a given topic, generally a specific command.

I mention this because this is an idea, a starting point, for designing this for halv3, but not necessarily the exact method we may want to go. For example, halibot core should not read and parse messages, so interpreting `!help` should _not_ be the responsibility of core. That said, other mechanisms can still be implemented in core, such as a registry of help topics.

Hint: module interactivity would be pretty nice here...

**Comment by sjrct** [comment]
To start, the help text should be on the package, probably in the `__init__.py` of the package. Then there should be a core module that processes `!help foo` command.

**Comment by richteer** [comment]
Not sure help text sure be in the `__init__.py`. With the discussions of moving functionality out of `main.py` and into modules, I think the text should remain owned by the actual module/agent object itself. That said, we can probably define more appropriate styles for where to write the help text itself (e.g. have them defined by variables that are referenced, rather than including a large blob of text in the middle of the class object)

**Comment by sjrct** [comment]
#91 closes this
