### ISSUE TITLE
add/remove should be on Halibot object

### ISSUE THREAD

**Issue by sjrct** [Halibot/halibot#69]
The adding and removing of modules and agents should probably exist on the Halibot object instead of in main.py so if the Halibot instance is running it can add/remove/update existing module/agent instances without have to reinitialize anything. Can then have a debugger agent that listens for input from the CLI and updates the halibot object accordingly, and can also have an admin module so that we can update the instance from an arbitrary agent through an arbitrary agent (e.g. IRC).

This goes in conjunction with #67 

Comments?

**Comment by richteer** [comment]
Per discussion in one of the meetings, the functionally should be potentially in a module, and the CLI `main.py` should contact a running instance via a local socket, or spin up a barebones instance to make the config changes and exit.

**Comment by richteer** [comment]
Marking stale. With proposed CLI changes, and the new `Config()` class, I don't think this is relevant anymore.

**Comment by sjrct** [comment]
Yeah, subset of the real solution with is the CLI overhaul and modularization.
